package cn.fuzhu.toolkit.modules;

import cn.fuzhu.toolkit.FuzhuToolkitPlugin;
import cn.fuzhu.toolkit.module.AbstractModule;
import org.bukkit.*;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.event.*;
import org.bukkit.event.inventory.InventoryCloseEvent;
import org.bukkit.inventory.ItemStack;
import java.util.*;

public final class AdditionalModules {
    private AdditionalModules() {}
    static abstract class M extends AbstractModule { M(FuzhuToolkitPlugin p){super(p);config=p.moduleConfig(id());} Player p(CommandSender s){return ModuleUtil.player(plugin,s);} boolean admin(CommandSender s){if(!s.hasPermission("fuzhu.admin")){plugin.msg(s,"&c你没有权限。");return false;}return true;} }
    public static final class Ping extends M { public Ping(FuzhuToolkitPlugin p){super(p);} public String id(){return "Ping";} public String description(){return "查看个人网络延迟";} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p!=null)plugin.msg(s,"&bPing: &f"+p.getPing()+"ms");return true;} }
    public static final class Online extends M { public Online(FuzhuToolkitPlugin p){super(p);} public String id(){return "Online";} public String description(){return "查看在线玩家";} public boolean handle(CommandSender s,String l,String[] a){List<String> n=Bukkit.getOnlinePlayers().stream().map(Player::getName).sorted().toList();plugin.msg(s,"&b在线玩家 (&f"+n.size()+"&b): &f"+(n.isEmpty()?"无":String.join(", ",n)));return true;} }
    public static final class Trash extends M { private Listener listener; public Trash(FuzhuToolkitPlugin p){super(p);} public String id(){return "Trash";} public String description(){return "打开丢弃物品界面";} public void enable(){super.enable();listener=new Listener(){@EventHandler public void close(InventoryCloseEvent e){if(e.getView().getTitle().equals("§8腐竹工具箱·垃圾桶"))e.getInventory().clear();}};plugin.getServer().getPluginManager().registerEvents(listener,plugin);} public void disable(){if(listener!=null)HandlerList.unregisterAll(listener);super.disable();} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p!=null)p.openInventory(Bukkit.createInventory(p,27,"§8腐竹工具箱·垃圾桶"));return true;} }
    public static final class Condense extends M { private final Map<Material,Material> recipes=Map.of(Material.IRON_INGOT,Material.IRON_BLOCK,Material.GOLD_INGOT,Material.GOLD_BLOCK,Material.COPPER_INGOT,Material.COPPER_BLOCK,Material.DIAMOND,Material.DIAMOND_BLOCK,Material.EMERALD,Material.EMERALD_BLOCK,Material.COAL,Material.COAL_BLOCK); public Condense(FuzhuToolkitPlugin p){super(p);} public String id(){return "Condense";} public String description(){return "将九个材料压缩为方块";} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p==null)return true;int total=0;for(var e:recipes.entrySet()){int count=p.getInventory().all(e.getKey()).values().stream().mapToInt(ItemStack::getAmount).sum();int blocks=count/9;if(blocks>0){p.getInventory().removeItem(new ItemStack(e.getKey(),blocks*9));p.getInventory().addItem(new ItemStack(e.getValue(),blocks));total+=blocks;}}plugin.msg(s,total>0?"&a已压缩 &f"+total+" &a个方块。":"&e没有足够材料（每种需要9个）。");return true;} }
    public static final class More extends M { public More(FuzhuToolkitPlugin p){super(p);} public String id(){return "More";} public String description(){return "将手中物品补满一组";} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p==null)return true;ItemStack i=p.getInventory().getItemInMainHand();if(i.getType().isAir()){plugin.msg(s,"&c手中没有物品。");return true;}i.setAmount(i.getMaxStackSize());plugin.msg(s,"&a物品已补满。");return true;} }
    public static final class GlobalTime extends M { public GlobalTime(FuzhuToolkitPlugin p){super(p);} public String id(){return "GlobalTime";} public String description(){return "设置当前世界时间";} public boolean handle(CommandSender s,String l,String[] a){if(!admin(s))return true;Player p=p(s);if(p==null)return true;if(a.length<1){plugin.msg(s,"&e/gtime day|night|noon");return true;}long t=switch(a[0].toLowerCase(Locale.ROOT)){case "night"->18000L;case "noon"->6000L;default->1000L;};p.getWorld().setTime(t);plugin.broadcast("&b世界时间已设置。");return true;} }
    public static final class Top extends M { public Top(FuzhuToolkitPlugin p){super(p);} public String id(){return "Top";} public String description(){return "传送到当前位置最高安全点";} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p==null)return true;Location o=p.getLocation();Location d=new Location(p.getWorld(),o.getBlockX()+.5,p.getWorld().getHighestBlockYAt(o.getBlockX(),o.getBlockZ())+1,o.getBlockZ()+.5);if(d.getBlock().isPassable()&&d.clone().add(0,1,0).getBlock().isPassable()){p.teleport(d);plugin.msg(s,"&a已传送至最高安全点。");}else plugin.msg(s,"&c没有安全落脚点。");return true;} }
    public static final class Depth extends M { public Depth(FuzhuToolkitPlugin p){super(p);} public String id(){return "Depth";} public String description(){return "查看当前高度范围";} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p!=null)plugin.msg(s,"&b高度: &f"+p.getLocation().getBlockY()+" &7| 世界: &f"+p.getWorld().getMinHeight()+"~"+p.getWorld().getMaxHeight()+" &7| 海平面: &f"+p.getWorld().getSeaLevel());return true;} }
    public static final class ItemName extends M { public ItemName(FuzhuToolkitPlugin p){super(p);} public String id(){return "ItemName";} public String description(){return "修改手中物品名称";} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p==null)return true;ItemStack i=p.getInventory().getItemInMainHand();if(i.getType().isAir()||a.length<1){plugin.msg(s,"&e/itemname <名称>");return true;}var m=i.getItemMeta();m.setDisplayName(plugin.color(ModuleUtil.join(a,0)));i.setItemMeta(m);plugin.msg(s,"&a物品名称已更新。");return true;} }
    public static final class ItemLore extends M { public ItemLore(FuzhuToolkitPlugin p){super(p);} public String id(){return "ItemLore";} public String description(){return "为手中物品添加说明";} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p==null)return true;ItemStack i=p.getInventory().getItemInMainHand();if(i.getType().isAir()||a.length<1){plugin.msg(s,"&e/itemlore <说明>");return true;}var m=i.getItemMeta();List<String> lore=m.hasLore()?new ArrayList<>(m.getLore()):new ArrayList<>();lore.add(plugin.color(ModuleUtil.join(a,0)));m.setLore(lore);i.setItemMeta(m);plugin.msg(s,"&a物品说明已添加。");return true;} }
}
