package cn.fuzhu.toolkit.modules;

import cn.fuzhu.toolkit.FuzhuToolkitPlugin;
import cn.fuzhu.toolkit.module.AbstractModule;
import org.bukkit.*;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.event.*;
import org.bukkit.event.player.AsyncPlayerChatEvent;
import org.bukkit.event.player.PlayerQuitEvent;
import org.bukkit.inventory.ItemStack;
import org.bukkit.event.inventory.InventoryType;
import org.bukkit.inventory.meta.Damageable;
import java.util.*;

/** Additional built-in modules. Each nested class is independently switchable. */
public final class ExtraModules {
    private ExtraModules() {}
    static abstract class M extends AbstractModule { M(FuzhuToolkitPlugin p){super(p);config=p.moduleConfig(id());} Player p(CommandSender s){return ModuleUtil.player(plugin,s);} boolean admin(CommandSender s){if(!s.hasPermission("fuzhu.admin")){plugin.msg(s,"&c你没有权限。");return false;}return true;} }
    public static final class RulesModule extends M { public RulesModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "Rules";} public String description(){return "查看服务器规则";} public boolean handle(CommandSender s,String l,String[] a){plugin.msg(s,"&b服务器规则");plugin.msg(s,"&f1. 遵守社区规范");plugin.msg(s,"&f2. 禁止作弊与恶意刷屏");plugin.msg(s,"&f3. 保护他人建筑与财产");return true;} }
    public static final class MotdModule extends M { public MotdModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "Motd";} public String description(){return "查看服务器公告";} public boolean handle(CommandSender s,String l,String[] a){plugin.msg(s,plugin.getConfig().getString("motd","&b欢迎来到服务器！"));return true;} }
    public static final class AfkModule extends M { private final Set<UUID> afk=new HashSet<>(); public AfkModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "Afk";} public String description(){return "切换挂机状态";} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p==null)return true;if(afk.remove(p.getUniqueId()))plugin.broadcast("&f"+p.getName()+" &a已取消挂机");else{afk.add(p.getUniqueId());plugin.broadcast("&f"+p.getName()+" &e正在挂机");}return true;} }
    public static final class NearModule extends M { public NearModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "Near";} public String description(){return "查看附近玩家";} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p==null)return true;int r=50;try{if(a.length>0)r=Math.min(200,Math.max(1,Integer.parseInt(a[0])));}catch(Exception ignored){}List<String> names=new ArrayList<>();for(Player x:Bukkit.getOnlinePlayers())if(x!=p&&x.getWorld()==p.getWorld()&&x.getLocation().distanceSquared(p.getLocation())<=r*r)names.add(x.getName());plugin.msg(s,"&b"+(names.isEmpty()?"附近没有玩家":"附近玩家: &f"+String.join(", ",names)));return true;} }
    public static final class TpaModule extends M { private final Map<UUID,UUID> requests=new HashMap<>(); public TpaModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "Tpa";} public String description(){return "/tpa、/tpaccept、/tpdeny 传送请求";} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p==null)return true;if(l.equalsIgnoreCase("tpa")){if(a.length<1){plugin.msg(s,"&e/tpa <玩家>");return true;}Player target=Bukkit.getPlayerExact(a[0]);if(target==null){plugin.msg(s,"&c玩家不在线。");return true;}requests.put(target.getUniqueId(),p.getUniqueId());plugin.msg(s,"&a已向 "+target.getName()+" 发送请求。");plugin.msg(target,"&e"+p.getName()+" 请求传送到你，使用 /tpaccept 或 /tpdeny");}else{UUID from=requests.remove(p.getUniqueId());if(from==null){plugin.msg(s,"&e没有待处理请求。");return true;}Player source=Bukkit.getPlayer(from);if(source==null){plugin.msg(s,"&c请求者已离线。");return true;}if(l.equalsIgnoreCase("tpaccept")){source.teleport(p);plugin.msg(source,"&a传送成功。");plugin.msg(s,"&a已接受请求。");}else{plugin.msg(source,"&c你的传送请求被拒绝。");plugin.msg(s,"&a已拒绝请求。");}}return true;} }
    public static final class RtpModule extends M { public RtpModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "Rtp";} public String description(){return "随机安全传送";} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p==null)return true;int r=1000;try{if(a.length>0)r=Math.min(5000,Math.max(50,Integer.parseInt(a[0])));}catch(Exception ignored){}World w=p.getWorld();Random random=new Random();int x=p.getLocation().getBlockX()+random.nextInt(r*2+1)-r,z=p.getLocation().getBlockZ()+random.nextInt(r*2+1)-r,y=w.getHighestBlockYAt(x,z)+1;Location loc=new Location(w,x+0.5,y,z+0.5);if(loc.getBlock().isPassable()&&loc.clone().add(0,1,0).getBlock().isPassable()){p.teleport(loc);plugin.msg(s,"&a随机传送成功。");}else plugin.msg(s,"&c未找到安全位置，请重试。");return true;} }
    public static final class InvseeModule extends M { public InvseeModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "Invsee";} public String description(){return "查看玩家背包";} public boolean handle(CommandSender s,String l,String[] a){if(!admin(s))return true;if(a.length<1){plugin.msg(s,"&e/invsee <玩家>");return true;}Player target=Bukkit.getPlayerExact(a[0]);Player p=p(s);if(target==null||p==null){plugin.msg(s,"&c玩家不在线。");return true;}p.openInventory(target.getInventory());return true;} }
    public static final class EnderChestModule extends M { public EnderChestModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "EnderChest";} public String description(){return "打开末影箱";} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p!=null)p.openInventory(p.getEnderChest());return true;} }
    public static final class FlyModule extends M { public FlyModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "Fly";} public String description(){return "切换飞行模式";} public boolean handle(CommandSender s,String l,String[] a){if(!admin(s))return true;Player p=p(s);if(p!=null){p.setAllowFlight(!p.getAllowFlight());p.setFlying(p.getAllowFlight());plugin.msg(s,"&a飞行模式: "+(p.getAllowFlight()?"开启":"关闭"));}return true;} }
    public static final class GameModeModule extends M { public GameModeModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "GameMode";} public String description(){return "切换游戏模式";} public boolean handle(CommandSender s,String l,String[] a){if(!admin(s))return true;Player p=p(s);if(p==null)return true;if(a.length<1){plugin.msg(s,"&e/gm survival|creative|adventure|spectator");return true;}try{p.setGameMode(GameMode.valueOf(a[0].toUpperCase(Locale.ROOT)));plugin.msg(s,"&a游戏模式已更新。");}catch(IllegalArgumentException e){plugin.msg(s,"&c未知模式。");}return true;} }
    public static final class NickModule extends M { public NickModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "Nick";} public String description(){return "设置显示昵称";} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p==null)return true;if(a.length<1){plugin.msg(s,"&e/nick <昵称>");return true;}String n=plugin.color(String.join(" ",a));p.setDisplayName(n);p.setPlayerListName(n);plugin.msg(s,"&a昵称已设置为 "+n);return true;} }
    public static final class RepairModule extends M { public RepairModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "Repair";} public String description(){return "修复手中物品";} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p==null)return true;ItemStack item=p.getInventory().getItemInMainHand();if(item.getType().isAir()||!(item.getItemMeta() instanceof Damageable d)){plugin.msg(s,"&c手中物品不可修复。");return true;}d.setDamage(0);item.setItemMeta(d);plugin.msg(s,"&a物品已修复。");return true;} }
    public static final class HatModule extends M { public HatModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "Hat";} public String description(){return "将手中物品戴在头上";} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p==null)return true;ItemStack hand=p.getInventory().getItemInMainHand(), head=p.getInventory().getHelmet();if(hand.getType().isAir()){plugin.msg(s,"&c手中没有物品。");return true;}p.getInventory().setHelmet(hand);p.getInventory().setItemInMainHand(head==null?new ItemStack(Material.AIR):head);plugin.msg(s,"&a已更换帽子。");return true;} }
    public static final class AnvilModule extends M { public AnvilModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "Anvil";} public String description(){return "打开铁砧界面";} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p!=null)p.openInventory(Bukkit.createInventory(p,InventoryType.ANVIL));return true;} }
    public static final class CraftModule extends M { public CraftModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "Craft";} public String description(){return "打开工作台界面";} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p!=null)p.openWorkbench(p.getLocation(),true);return true;} }
    public static final class KitModule extends M { public KitModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "Kit";} public String description(){return "领取新手礼包";} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p==null)return true;if(a.length<1||!a[0].equalsIgnoreCase("starter")){plugin.msg(s,"&e/kit starter");return true;}p.getInventory().addItem(new ItemStack(Material.IRON_SWORD),new ItemStack(Material.IRON_PICKAXE),new ItemStack(Material.BREAD,16));plugin.msg(s,"&a新手礼包已发放。");return true;} }
    public static final class VanishModule extends M { private final Set<UUID> hidden=new HashSet<>(); public VanishModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "Vanish";} public String description(){return "管理员隐身";} public boolean handle(CommandSender s,String l,String[] a){if(!admin(s))return true;Player p=p(s);if(p==null)return true;if(hidden.add(p.getUniqueId())){for(Player x:Bukkit.getOnlinePlayers())if(!x.hasPermission("fuzhu.admin"))x.hidePlayer(plugin,p);plugin.msg(s,"&a已隐身。");}else{hidden.remove(p.getUniqueId());for(Player x:Bukkit.getOnlinePlayers())x.showPlayer(plugin,p);plugin.msg(s,"&a已解除隐身。");}return true;} }
    public static final class ChatColorModule extends M { private final Map<UUID,ChatColor> colors=new HashMap<>(); private Listener listener; public ChatColorModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "ChatColor";} public String description(){return "设置聊天颜色";} public void enable(){super.enable();listener=new Listener(){@EventHandler public void chat(AsyncPlayerChatEvent e){ChatColor c=colors.get(e.getPlayer().getUniqueId());if(c!=null)e.setMessage(c+e.getMessage()+ChatColor.RESET);}@EventHandler public void quit(PlayerQuitEvent e){colors.remove(e.getPlayer().getUniqueId());}};plugin.getServer().getPluginManager().registerEvents(listener,plugin);} public void disable(){if(listener!=null)HandlerList.unregisterAll(listener);super.disable();} public boolean handle(CommandSender s,String l,String[] a){Player p=p(s);if(p==null)return true;if(a.length<1){plugin.msg(s,"&e/chatcolor red|green|aqua|yellow|white|reset");return true;}if(a[0].equalsIgnoreCase("reset")){colors.remove(p.getUniqueId());}else try{colors.put(p.getUniqueId(),ChatColor.valueOf(a[0].toUpperCase(Locale.ROOT)));}catch(Exception e){plugin.msg(s,"&c未知颜色。");return true;}plugin.msg(s,"&a聊天颜色已更新。");return true;} }
    public static final class BroadcastModule extends M { public BroadcastModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "Broadcast";} public String description(){return "发送全服彩色广播";} public boolean handle(CommandSender s,String l,String[] a){if(!admin(s))return true;if(a.length<1){plugin.msg(s,"&e/broadcast <文本>");return true;}plugin.broadcast("&d"+ModuleUtil.join(a,0));return true;} }
    public static final class ServerStatsModule extends M { public ServerStatsModule(FuzhuToolkitPlugin p){super(p);} public String id(){return "ServerStats";} public String description(){return "查看TPS、在线人数和内存";} public boolean handle(CommandSender s,String l,String[] a){Runtime r=Runtime.getRuntime();long used=(r.totalMemory()-r.freeMemory())/1024/1024;double tps=plugin.getServer().getTPS()[0];plugin.msg(s,"&b在线: &f"+Bukkit.getOnlinePlayers().size()+" &7| TPS: &f"+String.format(Locale.ROOT,"%.2f",tps)+" &7| 内存: &f"+used+"MB");return true;} }
}
